// This file is used as a template for the generated service worker by vite-plugin-pwa
// It will be processed by Workbox during the build
// The actual service worker logic will be generated by vite-plugin-pwa

// You don't need to manually add any code here. The configuration in vite.config.js
// handles the service worker generation and configuration.
registerRoute(
  ({ request }) =>
    request.destination === "style" || request.destination === "script",
  new StaleWhileRevalidate({
    cacheName: "static-resources",
  })
);

// Cachear datos de la API con NetworkFirst y BackgroundSync
registerRoute(
  ({ url }) => url.pathname.startsWith("/src/api/"),
  new NetworkFirst({
    cacheName: "api-data",
    plugins: [
      new BackgroundSyncPlugin("api-sync-queue", {
        maxRetentionTime: 24 * 60, // 24 horas
      }),
    ],
  })
);

self.addEventListener("sync", (event) => {
  if (event.tag === "api-sync-queue") {
    event.waitUntil(
      // Aquí iría la lógica para reenviar las peticiones fallidas
      console.log("Sincronizando datos encolados...")
    );
  }
});
